###############################
##### GLOBAL SETTINGS #########
###############################

Bind = "127.0.0.1:7667"
Debug = false
TLSBind = "127.0.0.1:7697"
TLSDir = "./etc/pki/tls/mattermost/"


##################################
##### MATTERMOST SETTINGS ########
##################################

[mattermost]
DefaultServer = "127.0.0.1:8065"
DefaultTeam = "i2p"
Insecure = true
JoinInclude = ["#town-square"]
PartFake = true
Restrict = ["127.0.0.1:8065"]
SkipTLSVerify = true
